### PR TITLE
Upgrade embulk-spi to 0.11, slf4j-api to 2.0.7, embulk-util-config to0.3.4, embulk-util-file to 0.1.5, embulk-util-text to 0.1.3

### PR DESCRIPTION
**Pull request by dmikurube**

### CODE REVIEW

**Comment by dmikurube** [comment]
It fails as of now, but it should be okay when `embulk-util-text:0.1.3` is ready.

**Comment by dmikurube** [comment]
Ready!

**Review by hiroyuki-sato — APPROVED** [review]
LGTM👍

**Comment by dmikurube** [comment]
Thanks!

**Pull request merged**
